### ISSUE TITLE
request object is undefined in lambda.js

### ISSUE THREAD

**Issue by deokjinkim** [SmartThingsCommunity/st-schema-nodejs#11]
When I tested lifx-connector(https://github.com/SmartThingsCommunity/st-schema-connectors/tree/master/lifx-connector) in aws lambda, request object is undefined.

https://github.com/SmartThingsCommunity/st-schema-nodejs/blob/c9482af705b4650658f547c97f219e0a2e7c3262/lib/lambda.js#L80

So I met below error message.
#### ERROR MESSAGE START ####
2019-05-26T23:53:19.544Z	32ad93e2-0f34-49e9-837f-6c4993444593	interactionType discoveryRequest
2019-05-26T23:53:19.545Z	32ad93e2-0f34-49e9-837f-6c4993444593	ERROR IN ST-SCHEMA HELPER TypeError: Cannot read property 'authentication' of undefined
    at Object.discoveryRequest (/var/task/index.js:9:84)
    at /var/task/node_modules/st-schema/lib/lambda.js:82:34      await opts[interactionType](request, response);
#### ERROR MESSAGE END ####

I think below line is needed before line 80.
request = event;

What do you think?

**Comment by workingmonk** [comment]
@deokjinkim we recently fixed a few of these issues in 1.1.2. Can you test if you are still seeing the issue?
